###################
## 필수 arguments ##
###################
model_name: "$MODEL_DIR" # local huggingface model directory, selfrag/llama2_7b를 환경변수로 저장하였음
input_file: "qa_data/input.json"
output_file: "results/output.json"
task: "asqa"

###################
## 선택 arguments ##
###################
ndocs: 3
max_new_tokens: 50
threshold: 0.4
w_rel: 1.0
w_sup: 2.0
w_use: 0.5
