#################
### NLI #########
#################
qa_in_dir: "db/qa_data/qa_from_lumber/all"
qa_filt_dir: "db/qa_data/qa_from_lumber/"
MAX_QA: 10000000000000

nli_cd_threshold: 0.9
nli_qa_threshold: 0.9

nli_model: "MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"

#################
### ROUGE #######
#################
#tokenizer_name: "moses" # 다국어용
tokenizer_name: "kiwi" # 한국어 전용
#tokenizer_name: "spacy" # 영어용 


##################
### BERT #########
##################
bert_num_layers: 9

#bert_model_name : bert-base-multilingual-cased # 다국어 지원
#bert_model_name : "bert-base-uncased" # 영어 전용
bert_model_name: "klue/bert-base" # 한국어 전용 1) KLUE BERT
#bert_model_name: "snunlp/KR-BERT-char16424" # 서울대 개발 한국어 전용 2) KR-BERT


#################
### SBERT #########
##################
#sbert_model_name : "intfloat/multilingual-e5-large" # 다국어 지원
#sbert_model_name: "sentence-transformers/all-mpnet-base-v2" # 영어 전용
sbert_model_name : "snunlp/KR-SBERT-V40K-klueNLI-augSTS" # 서울대 개발한 한국어 전용
#sbert_model_name : "jhgan/ko-sbert-sts" # 한국어 전용
#sbert_model_name : "jhgan/ko-sroberta-multitask" # 한국어 전용


##################
### BLEURT #######
##################
bleurt_model_name : "bleurt-base-128" # 다국어 없음, only 영어