#################
### Trimming ##
#################
search_dirs:
  # - "db/raw_db_extracted_paddle/"
  # - "db/raw_db_extracted/consulting_2022_02"
  # - "db/raw_db_extracted/consulting_2022_04"
  # - "db/raw_db_extracted/consulting_2024_(1)"
  # - "db/raw_db_extracted/consulting_2024_(2)"

output_dir: "db/md_for_synthesis/"

headers:
  - "# 1차 현장컨설팅 결과보고서"
  - "# 1 차 현장컨설팅 결과보고서"
  - "# l차 현장컨설팅 결과보고서"
  - "## 1차 현장컨설팅 결과보고서"
  - "# l 차 현장컨설팅 결과보고서"
  - "# 2차 현장컨설팅 결과보고서"
  - "# 2 차 현장컨설팅 결과보고서"
  - '<div style="text-align: center;">1차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">1차 현장컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장컨설팅 결과보고서</div>'

#################
### Extraction ##
#################
db_dirs:
  - "db/raw_db/in_use_manual/"
md_out_dir: "db/raw_db_extracted_paddle_manual/"

#################
### Chunking #####
#################
md_in_dirs:
  - "db/raw_db_extracted_paddle_manual/"
chunk_out_dir: "db/lumber_chunks_for_synthesis/"
max_fnum: 100000  # 테스트용, null이면 전체 처리

#################
### QA ##########
#################
chunk_in_dirs:
  - "db/lumber_chunks_for_synthesis/"
qa_out_dir: "db/qa_data/qa_lumber_chunks/"