#################
### Trimming ##
#################
search_dirs:
  # - "db/raw_db_extracted_paddle/"
  # - "db/raw_db_extracted/consulting_2022_02"
  # - "db/raw_db_extracted/consulting_2022_04"
  # - "db/raw_db_extracted/consulting_2024_(1)"
  # - "db/raw_db_extracted/consulting_2024_(2)"

output_dir: "db/md_for_synthesis/"

headers:
  - "# 1차 현장컨설팅 결과보고서"
  - "# 1 차 현장컨설팅 결과보고서"
  - "# l차 현장컨설팅 결과보고서"
  - "## 1차 현장컨설팅 결과보고서"
  - "# l 차 현장컨설팅 결과보고서"
  - "# 2차 현장컨설팅 결과보고서"
  - "# 2 차 현장컨설팅 결과보고서"
  - '<div style="text-align: center;">1차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">1차 현장컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장컨설팅 결과보고서</div>'

#################
### Chunking #####
#################

model_name: 'Qwen/Qwen2.5-7B-Instruct-GPTQ-Int8'

md_dirs:
   - "db/md_for_synthesis/"

  # - db/md_for_synthesis/fruit_diagnosis_manual
  # - "db/md_for_synthesis/consulting_2022_02"
  # - "db/md_for_synthesis/consulting_2022_04"
  # - "db/md_for_synthesis/consulting_2024_(1)"
  # - "db/md_for_synthesis/consulting_2024_(2)"

chunk_dir: "db/chunks_for_synthesis/"

max_fnum: 100000  # 테스트용, null이면 전체 처리

