#################
### Chunking #####
#################
md_in_dirs:
  #- "db/raw_db_extracted_paddle/"
  - "db/md_for_chunking/"
chunk_out_dir: "db/chunks_for_synthesis/"
max_fnum: 100000  # 테스트용, null이면 전체 처리

#################
### QA ##########
#################
chunk_in_dirs:
  - "db/chunks_for_synthesis/"
qa_out_dir: "db/qa_data/qa_from_lumber/"
MAX_QA: 10000000000000

#################
### NLI ##########
#################
qa_in_dir: "db/qa_data/qa_from_lumber/all"
qa_filt_dir: "db/qa_data/qa_from_lumber/"
MAX_QA: 10000000000000