embedor_model_name : "upskyy/bge-m3-korean" # only for 한국어
#embedor_model_name : "BAAI/bge-m3" # for 다국어

#################
### Trimming ##
#################
search_dirs:
   - "db/raw_db_extracted_paddle/"
  # - "db/raw_db_extracted/consulting_2022_02"
  # - "db/raw_db_extracted/consulting_2022_04"
  # - "db/raw_db_extracted/consulting_2024_(1)"
  # - "db/raw_db_extracted/consulting_2024_(2)"

output_dir: "db/md_for_synthesis/"

headers:
  - "# 1차 현장컨설팅 결과보고서"
  - "# 1 차 현장컨설팅 결과보고서"
  - "# l차 현장컨설팅 결과보고서"
  - "## 1차 현장컨설팅 결과보고서"
  - "# l 차 현장컨설팅 결과보고서"
  - "# 2차 현장컨설팅 결과보고서"
  - "# 2 차 현장컨설팅 결과보고서"
  - '<div style="text-align: center;">1차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">1차 현장컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장 컨설팅 결과보고서</div>'
  - '<div style="text-align: center;">2차 현장컨설팅 결과보고서</div>'

#################
### Extraction ##
#################
db_dirs:
  - "db/raw_db/in_use_manual/"
md_out_dir: "db/raw_db_extracted_paddle/"
