###################
## 필수 arguments ##
###################
input_file: "qa_data/input.json"
output_file: "results/output.json"
task: "asqa"

###################
## 선택 arguments ##
###################
ndocs: 3
max_new_tokens: 50
threshold: 0.4
w_rel: 1.0
w_sup: 2.0
w_use: 0.5


####################
## LLM 모델 설정 ####
###################
#model_name: "$MODEL_DIR" # local huggingface model directory, selfrag/llama2_7b를 환경변수로 저장하였음
#model_name: "yi:34b-chat"
model_name : "Qwen/Qwen2.5-32B-Instruct"
#model_name : "Qwen/Qwen2.5-32B-Instruct"
#model_name : "qwen2.5:72b-instruct"
#model_name : 'llama3:70b'
#model_name : 'qwen3:32b' # 얘는 말이 너무 많음
#model_name : 'exaone3.5:32b' # 한국어 최적화 국산 모델
#model_name : 'qwq:32b'
#model_name : 'mistral-nemo' # 12b 로컬용
#model_name : 'falcon:40b-instruct-q5_1' # 영어 최적화


####################
## EMBEDDER 모델 설정 
###################
#embedor_model_name: 'mixedbread-ai/mxbai-embed-large-v1' # 영어 embedor
#embedor_model_name: "dragonkue/BGE-m3-ko" # 한국어 전용 embedor
embedor_model_name: "upskyy/bge-m3-korean"


##################
## 평가 지표 설정 ###
##################
sbert_model_name : "snunlp/KR-SBERT-V40K-klueNLI-augSTS"
#sbert_model_name : "all-MiniLM-L6-v2"
#bert_model_name : "bert-base-uncased" # 영어 전용
bert_model_name : bert-base-multilingual-cased # 다국어 지원
#bert_model_name : xlm-roberta-large # 다국어 지원2 hugging face 모델, 근데 에러남
